// Loding
export const DATA_LOADING = 'DATA_LOADING';
export const DATA_FAILED = 'DATA_FAILED';

// Login, Logout & Signup
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// All
export const ALL_STORIES_SUCCESS = 'ALL_STORIES_SUCCESS';
export const USER_STORIES_SUCCESS = 'USER_STORIES_SUCCESS';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const ALL_USER_LIST_SUCCESS = 'ALL_USER_LIST_SUCCESS';
